name: Update Sponsors Files

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update sponsors files
        uses: ./.github/actions/sponsors-update
        with:
          files-to-update: "templates/README.md.tpl"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(sponsors): update sponsors"
          file_pattern: "*.md.tpl"
